---API EXAMPLE PROJECT---


In [7]:
import request
import json
import math

def episodeCount(species, status):
    """
    Function to filter Rick and Morty characters based on species and status, and return the minimum and maximum number of episodes in which the filtered characters have appeared.

    Args:
        species (str): The species to filter characters by (e.g., "Human", "Alien").
        status (str): The status to filter characters by (e.g., "Alive", "Dead", "unknown").

    Returns:
        list: A list containing two integers representing the minimum and maximum episode counts among the filtered characters.              
If no characters match the criteria, returns [0, 0].

    Raises:
        Exception: If there is an issue with the HTTP request or JSON parsing.
    """


    # Initialize the minimum and maximum episode counts
    min_episodes = float('inf')
    max_episodes = float('-inf')

    try:
        # Rick and Morty API endpoint for characters
        url = "https://rickandmortyapi.com/api/character/"
        page = 1 # Start from the first page

        # Iterate through all pages of the API response
        while True:
            # Make an HTTP GET request, passing the current page number as a query parameter
            response = request.get(url, params={'page': page})
            response.raise_for_status() # Handle HTTP errors
            data = response.json()      # Parse the JSON response

            # Extract the list of characters from the response
            {UPDATE}
            if not characters:
                # If there are no more characters, exit the loop
                {UPDATE}

            # Iterate through each character record in the current page
            {UPDATE}
                # Filter records based on species and status
                {UPDATE} and {UPDATE}
                    # Count the number of episodes in which the character appears
                    {UPDATE}
                    # Update the minimum and maximum episode counts
                    min_episodes = min (min_episodes, episode_count)
                    max_episodes = max (max_episodes, episode_count)

            # Check if there is a next page; if not, break out of the loop.
            {UPDATE}

            # Move to the next page
            page += 1

    except Exception as e:
        # If there is any error during the request or processing, raise an exception.
        {UPDATE} Exception("An error occurred: " + str(e))

    # If no matching characters were found, return [0, 0]
    if min_episodes == float('inf') and max_episodes == float('-inf'):
        {UPDATE}

    # Return the integer values of the minimum and maximum episode counts.
    return {UPDATE}

# Example usage:
species_filter = "Human"
status_filter = "Alive"
result = episodeCount(species_filter, status_filter)
print("Minimum Episode Count:", result[0])
print("Maximum Episode Count:", result[1])



IndentationError: unexpected indent (2354107997.py, line 47)

In [8]:
import requests
import json
import math

def episopeCount(species, status):
    """
        Function to filter Rick and Morty characters based on species and status, and return the minimum and maximum number of episodes in which the filtered characters have appeared.
    """

    # Args:
    # species (str): the species to filter characters by (e.g., "Human", "Alien").
    # status (str): The status to filter characters by (e.g., "Alive", "Dead", "unknown").
    # Returns:
    # list: A list containing two integers representing the minimum and maximum episode count among the filtered characters.
    # If no characters match the criteria, return [0, 0].
    # Raises:
    # requests.exceptions.RequestException: If there is an issue with the HTTP request.
    # json.JSONDecodeError: If there is an issue with JSON parsing.
    # """

    # Initialize the minimum and maximum episode counts
    min_episodes = float('inf')
    max_episodes = float('-inf')
    found_character = False
    # Rick and Morty API endpoint for characters
    try:
        url = "https://rickandmortyapi.com/api/character/"
        page = 1 # Start from the first page

        # Iterate through all pages of the API response
        while True:
            response = requests.get(url, params={'page': page})
            response.raise_for_status()  # Raise an exception for bad status codes
            data = response.json()

            for character in data['results']:
                if character['species'] == species and character['status'].lower() == status.lower():
                    found_character = True
                    episode_count = len(character['episode'])
                    min_episodes = min(min_episodes, episode_count)
                    max_episodes = max(max_episodes, episode_count)

            if data['info']['next']:
                page += 1
            else:
                break

        if not found_character:
            return [0, 0]
        else:
            return [min_episodes, max_episodes]

    except requests.exceptions.RequestException as e:
        raise Exception(f"Error during HTTP request: {e}")
    except json.JSONDecodeError as e:
        raise Exception(f"Error decoding JSON response: {e}")

# Example usage:
try:
    episode_range = episopeCount("Human", "Alive")
    print(f"Episode count range for alive Humans: {episode_range}")

    episode_range = episopeCount("Alien", "Dead")
    print(f"Episode count range for dead Aliens: {episode_range}")

    episode_range = episopeCount("Robot", "unknown")
    print(f"Episode count range for unknown Robots: {episode_range}")

    episode_range = episopeCount("Mythological Creature", "Alive")
    print(f"Episode count range for alive Mythological Creatures: {episode_range}")

except Exception as e:
    print(f"An error occurred: {e}")


Episode count range for alive Humans: [1, 51]
Episode count range for dead Aliens: [1, 3]
Episode count range for unknown Robots: [1, 1]
Episode count range for alive Mythological Creatures: [1, 3]


In [1]:
import requests

def episodeCount(species, status):
    """
    Function to filter Rick and Morty characters based on species and status,
    and return the minimum and maximum number of episodes in which the filtered characters have appeared.

    Args:
        species (str): The species to filter characters by (e.g., "Human", "Alien").
        status (str): The status to filter characters by (e.g., "Alive", "Dead", "unknown").

    Returns:
        list: A list containing two integers representing the minimum and maximum episode counts among the filtered characters.
              If no characters match the criteria, returns [0, 0].

    Raises:
        Exception: If there is an issue with the HTTP request or JSON parsing.
    """
    # Initialize the minimum and maximum episode counts
    min_episodes = float('inf')
    max_episodes = float('-inf')

    try:
        # Rick and Morty API endpoint for characters
        url = "https://rickandmortyapi.com/api/character/"
        page = 1  # Start from the first page

        # Iterate through all pages of the API response
        while True:
            # Make an HTTP GET request, passing the current page number as a query parameter
            response = requests.get(url, params={"page": page})
            response.raise_for_status()  # Handle HTTP errors
            data = response.json()       # Parse the JSON response

            # Extract the list of characters from the response
            characters = data.get("results", [])
            if not characters:
                # If there are no more characters, exit the loop
                break

            # Iterate through each character record in the current page
            for character in characters:
                # Filter records based on species and status
                if character.get("species") == species and character.get("status") == status:
                    # Count the number of episodes in which the character appears
                    ep_count = len(character.get("episode", []))
                    # Update the minimum and maximum episode counts
                    min_episodes = min(min_episodes, ep_count)
                    max_episodes = max(max_episodes, ep_count)

            # Check if there is a next page; if not, break out of the loop.
            info = data.get("info", {})
            if not info.get("next"):
                break

            # Move to the next page
            page += 1

    except Exception as e:
        # If there is any error during the request or processing, raise an exception.
        raise Exception("An error occurred: " + str(e))

    # If no matching characters were found, return [0, 0]
    if min_episodes == float('inf') and max_episodes == float('-inf'):
        return [0, 0]

    # Return the integer values of the minimum and maximum episode counts.
    return [int(min_episodes), int(max_episodes)]

# Example usage:
species_filter = "Human"
status_filter = "Alive"
result = episodeCount(species_filter, status_filter)
print("Minimum Episode Count:", result[0])
print("Maximum Episode Count:", result[1])

Minimum Episode Count: 1
Maximum Episode Count: 51


In [1]:
!pip install numpy

   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   --------------------------- ------------ 8.7/12.6 MB 45.9 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 43.3 MB/s eta 0:00:00


In [3]:
import numpy as np

---CREATE---

In [5]:
data = np.random.rand(2,3,4)
zeroes = np.zeros((2,2,2))
full = np.full((2,2,2), 7)
ones = np.ones((2,2,2))
data

array([[[0.55210088, 0.65965471, 0.58156886, 0.01313803],
        [0.18084891, 0.83664275, 0.72879904, 0.25029644],
        [0.22347343, 0.63528907, 0.53568245, 0.75325559]],

       [[0.00436874, 0.66668933, 0.55482488, 0.41473376],
        [0.28789109, 0.12971141, 0.75018074, 0.71781998],
        [0.37466636, 0.57892129, 0.03806561, 0.20967538]]])

In [7]:
zeroes

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [8]:
ones

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [14]:
arr = np.array([[1,2,3,4,], [1,2,3,4]])

type(arr)


numpy.ndarray

In [18]:
shape = data.shape
size = data.size
types = data.dtype

types

dtype('float64')

In [22]:
arr = data[0]
slicer = data[0:2]
reverse = data[-1]
singleval = data [0] [0] [0]

singleval

np.float64(0.5521008753514942)

In [27]:
list1 = np.random.rand(10)
list2 = np.random.rand(10)

list2

array([0.34579751, 0.32968696, 0.70435268, 0.67253911, 0.04362642,
       0.56716095, 0.00231082, 0.65449725, 0.7485964 , 0.33983157])

In [31]:
add = np.add(list1, list2)
sub = np.subtract(list1, list2)
div = np. divide(list1 ,list2)
mult = np.multiply(list1, list2)
dot = np.dot(list1, list2)

sub

array([ 0.14297434,  0.44999583,  0.01847334,  0.20131827,  0.80453978,
       -0.01387731,  0.91985655, -0.54807738, -0.05105217,  0.25913062])

In [5]:
import numpy as np

arr = np.array([1, 2, 3])
print(arr)

arr = np.array([[1 ,2 ,3,],[4, 5, 6]])
print(arr)

arr=np.array((1, 3, 2))
print(arr)

[1 2 3]
[[1 2 3]
 [4 5 6]]
[1 3 2]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3])
print(arr)

arr = np.array([[1 ,2 ,3,],[4, 5, 6]])
print(arr)

arr=np.array((1, 3, 2))
print(arr)
# Printing a range of Array
# with the use of slicing method
arr = np.array([[-1, 2, 0, 4],[4, -0.5, 6, 0],[2.6, 0, 7, 8],[3, -7, 4, 2.0]])


In [8]:
import numpy as np

arr = np.array([[-1, 2, 0, 4],[4, -0.5, 6, 0],[2.6, 0, 7, 8],[3, -7, 4, 2.0]])
# Printing a range of Array
# with the use of slicing method
arr2= arr[:2, ::2]
print ("first 2 rows and alternate columns(0 and 2):\n", arr2)

arr3 = arr[[1, 1, 0, 3],[3, 2, 1, 0]]
print ("\nelements at indices (1, 3),""(1, 2),(0, 1),(3, 0):\n", arr3)

first 2 rows and alternate columns(0 and 2):
 [[-1.  0.]
 [ 4.  6.]]

elements at indices (1, 3),(1, 2),(0, 1),(3, 0):
 [0. 6. 2. 3.]


In [17]:
import numpy as np
# Defining Array 1
a = np.array([[1, 2],[3, 4]])

# Defining Array 2
b = np.array([[4, 3],[2, 1]])
#adding 1 to every element
print ("adding 1 to every element:" , a + 1)

# Subtracting 2 from each element
print ("\nSubtracting 2 from each element:", b - 2)
 
# sum of array elements
# Performing Unary operations
print ("\nSum of all array elements: ", a.sum())
 
# Adding two arrays
# Performing Binary operations


adding 1 to every element: [[2 3]
 [4 5]]

Subtracting 2 from each element: [[ 2  1]
 [ 0 -1]]

Sum of all array elements:  10
